version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: farm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  farm:
    image: farm-service
    ports:
      - "8080:8080"
    depends_on:
      - db