version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: farm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  farm:
    image: farm-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farm-service
    ports:
      - "8080:8080"
    depends_on:
      - db