version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: farm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=true
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  app:
    image: farm-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - jwt.token.key=relex-secret
      - jwt.token.time=6000000
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.username=testforrelexfarm@gmail.com
      - spring.mail.password=pbmotrtmarswpzut
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enabled=true
      - spring.mail.properties.mail.smtp.starttls.required=true
      - spring.data.redis.port=6379
      - spring.data.redis.host=redis
      - spring.data.redis.repositories.enabled=false